export const CREATE_MACHINE_CATEGORY = 'CREATE_MACHINE_CATEGORY';
export const DELETE_MACHINE_CATEGORY = 'DELETE_MACHINE_CATEGORY';
export const UPDATE_MACHINE_CATEGORY_NAME = 'UPDATE_MACHINE_CATEGORY_NAME';
export const VALIDATE_MACHINE_CATEGORY_NAME = 'VALIDATE_MACHINE_CATEGORY_NAME';
export const CREATE_MACHINE_ATTRIBUTE = 'CREATE_MACHINE_ATTRIBUTE';
export const DELETE_MACHINE_ATTRIBUTE = 'DELETE_MACHINE_ATTRIBUTE';
export const UPDATE_MACHINE_ATTRIBUTE_NAME = 'UPDATE_MACHINE_ATTRIBUTE_NAME';
export const VALIDATE_MACHINE_ATTRIBUTE_NAME =
  'VALIDATE_MACHINE_ATTRIBUTE_NAME';
export const UPDATE_MACHINE_ATTRIBUTE_VALUE_OPTION =
  'UPDATE_MACHINE_ATTRIBUTE_VALUE_OPTION';
export const UPDATE_MACHINE_TITLE_ATTRIBUTE = 'UPDATE_MACHINE_TITLE_ATTRIBUTE';
export const CREATE_MACHINE = 'CREATE_MACHINE';
export const DELETE_MACHINE = 'DELETE_MACHINE';
export const UPDATE_MACHINE_ATTRIBUTE_VALUE = 'UPDATE_MACHINE_ATTRIBUTE_VALUE';
export const CLEAR_CATEGORY_ERROR = 'CLEAR_CATEGORY_ERROR';

export interface ActionBase {
  type: string;
  payload?: any;
}
